### ISSUE TITLE
'AxesSubplot' object has no attribute 'set_axis_bgcolor'

### ISSUE THREAD

**Issue by luisgustavob78** [julioasotodv/spark-df-profiling#38]
I am not getting to run spark_df_profiling because 'set_axis_bgcolor' was replaced by set_facecolor. How can i repair that?

**Comment by victor-kironde** [comment]
Same issue, Looks like it was already solved!
@julioasotodv

**Comment by istvanszabo92** [comment]
Same issue here.

**Comment by victor-kironde** [comment]
@istvanszabo92  try reinstalling with pip

**Comment by dmoore247** [comment]
@istvanszabo92 set_axis_bgcolor was deprecated in matplotlib 2.x version.

**Comment by CarlaFernandez** [comment]
Hi, I've just installed spark-df-profiling==1.1.13 (latest version) using pip, and this error remains. 
@julioasotodv Any chance we can move this so it gets fixed? This library is very promising but right now it's unusable.
Muchas gracias.

**Comment by sshamid** [comment]
I'm seeing the same. After installing the latest version (1.1.13), I get the old source code in base.py (line 164)

        plot.set_axis_bgcolor("w")
`

**Comment by patrickcomerford** [comment]
same issues here, using spark-df-profiling  1.1.13 and matplotlib 3.0.3

` AttributeError: 'AxesSubplot' object has no attribute 'set_axis_bgcolor'`
